apiVersion: v1
kind: Pod
metadata:
  name: lab-pod
  labels:
    app: lab-pod
spec:
  containers:
  - env:
    - name: MESSAGE
      value: Hi! I'm name is itirngd
    image: quay.io/practicalopenshift/hello-world
    imagePullPolicy: Always
    name: hello-world-override
    resources: {}
